import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import connectMongoDB from './libs/mongodb'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  connectMongoDB()
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-3xl p-4 mx-auto'>
        <Navbar/>
        <div className='mt-8'>
        {children} 
        </div>
        </div>
        </body>
    </html>
  )
}
